# Generated by Django 5.0.7 on 2024-08-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_premium_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Blog', max_length=100)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('min_articles_for_writer', models.PositiveIntegerField(default=1)),
                ('min_followers_for_writer', models.PositiveIntegerField(default=1)),
                ('min_reactions_for_writer', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_manual_writer',
            field=models.BooleanField(default=False),
        ),
    ]
