# Generated by Django 5.0.7 on 2024-08-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sitesettings_user_is_manual_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_suggested_users',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_articles_for_suggestions',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='suggestion_cache_timeout',
            field=models.PositiveIntegerField(default=3600),
        ),
    ]
