# Generated by Django 5.0.7 on 2024-08-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_sitesettings_max_suggested_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onesignal_player_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
