# Generated by Django 5.0.7 on 2024-08-06 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_commentreaction_count'),
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'New Follower'), ('comment', 'New Comment'), ('comment_reaction', 'New Comment Reaction'), ('reply', 'New Reply'), ('clap', 'New Clap'), ('sad', 'New Sad Reaction'), ('laugh', 'New Laugh Reaction')], max_length=20),
        ),
    ]
