# Generated by Django 5.0.7 on 2024-08-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'New Follower'), ('comment', 'Commented on'), ('comment_reaction', 'Reacted to your comment on'), ('reply', 'Replied to your comment on'), ('clap', 'Reacted Clap on your post'), ('sad', 'Reacted Sad on your post'), ('laugh', 'Reacted Sad on your post'), ('mention', 'Mentioned you on')], max_length=20),
        ),
    ]
