# Generated by Django 5.0.7 on 2024-08-05 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
