# Generated by Django 5.0.7 on 2024-08-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
