# Generated by Django 5.0.7 on 2024-08-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_reaction_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
