# Generated by Django 5.0.7 on 2024-08-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_comment_parent_commentreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('clap', 'Clap'), ('laugh', 'Laugh'), ('sad', 'Sad')], max_length=5),
        ),
    ]
