# Generated by Django 5.0.7 on 2024-08-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_commentreaction_reaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreaction',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
