# Generated by Django 5.0.7 on 2024-08-08 17:27

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_mention_comment_mentioned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/', validators=[articles.models.validate_file_size]),
        ),
    ]
