# Generated by Django 5.0.7 on 2024-08-11 14:21

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='article_thumbnails/', validators=[articles.models.validate_file_size]),
        ),
    ]
